
;;;
;;; Enum Types
;;;

(define-foreign-enum-type (exceptiontype int)
  (exceptiontype->int int->exceptiontype)
  (exception/undefined UndefinedException)
  (exception/warning WarningException)
  (exception/resourcelimitwarning ResourceLimitWarning)
  (exception/typewarning TypeWarning)
  (exception/optionwarning OptionWarning)
  (exception/delegatewarning DelegateWarning)
  (exception/missingdelegatewarning MissingDelegateWarning)
  (exception/corruptimagewarning CorruptImageWarning)
  (exception/fileopenwarning FileOpenWarning)
  (exception/blobwarning BlobWarning)
  (exception/streamwarning StreamWarning)
  (exception/cachewarning CacheWarning)
  (exception/coderwarning CoderWarning)
  (exception/filterwarning FilterWarning)
  (exception/modulewarning ModuleWarning)
  (exception/drawwarning DrawWarning)
  (exception/imagewarning ImageWarning)
  (exception/wandwarning WandWarning)
  (exception/randomwarning RandomWarning)
  (exception/xserverwarning XServerWarning)
  (exception/monitorwarning MonitorWarning)
  (exception/registrywarning RegistryWarning)
  (exception/configurewarning ConfigureWarning)
  (exception/policywarning PolicyWarning)
  (exception/error ErrorException)
  (exception/resourcelimiterror ResourceLimitError)
  (exception/typeerror TypeError)
  (exception/optionerror OptionError)
  (exception/delegateerror DelegateError)
  (exception/missingdelegateerror MissingDelegateError)
  (exception/corruptimageerror CorruptImageError)
  (exception/fileopenerror FileOpenError)
  (exception/bloberror BlobError)
  (exception/streamerror StreamError)
  (exception/cacheerror CacheError)
  (exception/codererror CoderError)
  (exception/filtererror FilterError)
  (exception/moduleerror ModuleError)
  (exception/drawerror DrawError)
  (exception/imageerror ImageError)
  (exception/wanderror WandError)
  (exception/randomerror RandomError)
  (exception/xservererror XServerError)
  (exception/monitorerror MonitorError)
  (exception/registryerror RegistryError)
  (exception/configureerror ConfigureError)
  (exception/policyerror PolicyError)
  (exception/fatalerror FatalErrorException)
  (exception/resourcelimitfatalerror ResourceLimitFatalError)
  (exception/typefatalerror TypeFatalError)
  (exception/optionfatalerror OptionFatalError)
  (exception/delegatefatalerror DelegateFatalError)
  (exception/missingdelegatefatalerror MissingDelegateFatalError)
  (exception/corruptimagefatalerror CorruptImageFatalError)
  (exception/fileopenfatalerror FileOpenFatalError)
  (exception/blobfatalerror BlobFatalError)
  (exception/streamfatalerror StreamFatalError)
  (exception/cachefatalerror CacheFatalError)
  (exception/coderfatalerror CoderFatalError)
  (exception/filterfatalerror FilterFatalError)
  (exception/modulefatalerror ModuleFatalError)
  (exception/drawfatalerror DrawFatalError)
  (exception/imagefatalerror ImageFatalError)
  (exception/wandfatalerror WandFatalError)
  (exception/randomfatalerror RandomFatalError)
  (exception/xserverfatalerror XServerFatalError)
  (exception/monitorfatalerror MonitorFatalError)
  (exception/registryfatalerror RegistryFatalError)
  (exception/configurefatalerror ConfigureFatalError)
  (exception/policyfatalerror PolicyFatalError))

(define-foreign-enum-type (colorspace int)
  (colorspace->int int->colorspace)
  (colorspace/undefined UndefinedColorspace)
  (colorspace/rgb RGBColorspace)
  (colorspace/gray GRAYColorspace)
  (colorspace/transparent TransparentColorspace)
  (colorspace/ohta OHTAColorspace)
  (colorspace/lab LabColorspace)
  (colorspace/xyz XYZColorspace)
  (colorspace/ycbcr YCbCrColorspace)
  (colorspace/ycc YCCColorspace)
  (colorspace/yiq YIQColorspace)
  (colorspace/ypbpr YPbPrColorspace)
  (colorspace/yuv YUVColorspace)
  (colorspace/cmyk CMYKColorspace)
  (colorspace/srgb sRGBColorspace)
  (colorspace/hsb HSBColorspace)
  (colorspace/hsl HSLColorspace)
  (colorspace/hwb HWBColorspace)
  (colorspace/rec601luma Rec601LumaColorspace)
  (colorspace/rec601ycbcr Rec601YCbCrColorspace)
  (colorspace/rec709luma Rec709LumaColorspace)
  (colorspace/rec709ycbcr Rec709YCbCrColorspace)
  (colorspace/log LogColorspace)
  (colorspace/cmy CMYColorspace))

(define-foreign-enum-type (compressiontype int)
  (compressiontype->int int->compressiontype)
  (compression/undefined UndefinedCompression)
  (compression/none NoCompression)
  (compression/bzip BZipCompression)
  (compression/dxt1 DXT1Compression)
  (compression/dxt3 DXT3Compression)
  (compression/dxt5 DXT5Compression)
  (compression/fax FaxCompression)
  (compression/group4 Group4Compression)
  (compression/jpeg JPEGCompression)
  (compression/jpeg2000 JPEG2000Compression)
  (compression/losslessjpeg LosslessJPEGCompression)
  (compression/lzw LZWCompression)
  (compression/rle RLECompression)
  (compression/zip ZipCompression)
  (compression/zips ZipSCompression)
  (compression/piz PizCompression)
  (compression/pxr24 Pxr24Compression)
  (compression/b44 B44Compression)
  (compression/b44a B44ACompression)
  (compression/lzma LZMACompression)
  (compression/jbig1 JBIG1Compression)
  (compression/jbig2 JBIG2Compression))

(define-foreign-enum-type (gravity int)
  (gravity->int int->gravity)
  (gravity/undefined UndefinedGravity)
  (gravity/forget ForgetGravity)
  (gravity/northwest NorthWestGravity)
  (gravity/north NorthGravity)
  (gravity/northeast NorthEastGravity)
  (gravity/west WestGravity)
  (gravity/center CenterGravity)
  (gravity/east EastGravity)
  (gravity/southwest SouthWestGravity)
  (gravity/south SouthGravity)
  (gravity/southeast SouthEastGravity)
  (gravity/static StaticGravity))

(define-foreign-enum-type (interlacetype int)
  (interlacetype->int int->interlacetype)
  (interlace/undefined UndefinedInterlace)
  (interlace/none NoInterlace)
  (interlace/line LineInterlace)
  (interlace/plane PlaneInterlace)
  (interlace/partition PartitionInterlace)
  (interlace/gif GIFInterlace)
  (interlace/jpeg JPEGInterlace)
  (interlace/png PNGInterlace))

(define-foreign-enum-type (interpolatepixelmethod int)
  (interpolatepixelmethod->int int->interpolatepixelmethod)
  (interpolatepixel/undefined UndefinedInterpolatePixel)
  (interpolatepixel/average AverageInterpolatePixel)
  (interpolatepixel/bicubic BicubicInterpolatePixel)
  (interpolatepixel/bilinear BilinearInterpolatePixel)
  (interpolatepixel/filter FilterInterpolatePixel)
  (interpolatepixel/integer IntegerInterpolatePixel)
  (interpolatepixel/mesh MeshInterpolatePixel)
  (interpolatepixel/nearestneighbor NearestNeighborInterpolatePixel)
  (interpolatepixel/spline SplineInterpolatePixel))

(define-foreign-enum-type (orientation int)
  (orientation->int int->orientation)
  (orientation/undefined UndefinedOrientation)
  (orientation/topleft TopLeftOrientation)
  (orientation/topright TopRightOrientation)
  (orientation/bottomright BottomRightOrientation)
  (orientation/bottomleft BottomLeftOrientation)
  (orientation/lefttop LeftTopOrientation)
  (orientation/righttop RightTopOrientation)
  (orientation/rightbottom RightBottomOrientation)
  (orientation/leftbottom LeftBottomOrientation))

(define-foreign-enum-type (resourcetype int)
  (resourcetype->int int->resourcetype)
  (resource/undefined UndefinedResource)
  (resource/area AreaResource)
  (resource/disk DiskResource)
  (resource/file FileResource)
  (resource/map MapResource)
  (resource/memory MemoryResource)
  (resource/thread ThreadResource)
  (resource/time TimeResource)
  (resource/throttle ThrottleResource))

(define-foreign-enum-type (imagetype int)
  (imagetype->int int->imagetype)
  (type/undefined UndefinedType)
  (type/bilevel BilevelType)
  (type/grayscale GrayscaleType)
  (type/grayscalematte GrayscaleMatteType)
  (type/palette PaletteType)
  (type/palettematte PaletteMatteType)
  (type/truecolor TrueColorType)
  (type/truecolormatte TrueColorMatteType)
  (type/colorseparation ColorSeparationType)
  (type/colorseparationmatte ColorSeparationMatteType)
  (type/optimize OptimizeType)
  (type/palettebilevelmatte PaletteBilevelMatteType))

(define-foreign-enum-type (channeltype int)
  (channeltype->int int->channeltype)
  (channel/undefined UndefinedChannel)
  (channel/red RedChannel)
  (channel/gray GrayChannel)
  (channel/cyan CyanChannel)
  (channel/green GreenChannel)
  (channel/magenta MagentaChannel)
  (channel/blue BlueChannel)
  (channel/yellow YellowChannel)
  (channel/alpha AlphaChannel)
  (channel/opacity OpacityChannel)
  (channel/matte MatteChannel)
  (channel/black BlackChannel)
  (channel/index IndexChannel)
  (channel/composite CompositeChannels)
  (channel/all AllChannels)
  (channel/truealpha TrueAlphaChannel)
  (channel/rgb RGBChannels)
  (channel/gray GrayChannels)
  (channel/sync SyncChannels)
  (channel/default DefaultChannels))

(define-foreign-enum-type (noisetype int)
  (noisetype->int int->noisetype)
  (noise/undefined UndefinedNoise)
  (noise/uniform UniformNoise)
  (noise/gaussian GaussianNoise)
  (noise/multiplicativegaussian MultiplicativeGaussianNoise)
  (noise/impulse ImpulseNoise)
  (noise/laplacian LaplacianNoise)
  (noise/poisson PoissonNoise)
  (noise/random RandomNoise))

(define-foreign-enum-type (kernelinfotype int)
  (kernelinfotype->int int->kernelinfotype)
  (kernel/undefined UndefinedKernel)
  (kernel/unity UnityKernel)
  (kernel/gaussian GaussianKernel)
  (kernel/dog DoGKernel)
  (kernel/log LoGKernel)
  (kernel/blur BlurKernel)
  (kernel/comet CometKernel)
  (kernel/laplacian LaplacianKernel)
  (kernel/sobel SobelKernel)
  (kernel/freichen FreiChenKernel)
  (kernel/roberts RobertsKernel)
  (kernel/prewitt PrewittKernel)
  (kernel/compass CompassKernel)
  (kernel/kirsch KirschKernel)
  (kernel/diamond DiamondKernel)
  (kernel/square SquareKernel)
  (kernel/rectangle RectangleKernel)
  (kernel/octagon OctagonKernel)
  (kernel/disk DiskKernel)
  (kernel/plus PlusKernel)
  (kernel/cross CrossKernel)
  (kernel/ring RingKernel)
  (kernel/peaks PeaksKernel)
  (kernel/edges EdgesKernel)
  (kernel/corners CornersKernel)
  (kernel/diagonals DiagonalsKernel)
  (kernel/lineends LineEndsKernel)
  (kernel/linejunctions LineJunctionsKernel)
  (kernel/ridges RidgesKernel)
  (kernel/convexhull ConvexHullKernel)
  (kernel/thinse ThinSEKernel)
  (kernel/skeleton SkeletonKernel)
  (kernel/chebyshev ChebyshevKernel)
  (kernel/manhattan ManhattanKernel)
  (kernel/octagonal OctagonalKernel)
  (kernel/euclidean EuclideanKernel)
  (kernel/userdefined UserDefinedKernel))

(define-foreign-enum-type (metrictype int)
  (metrictype->int int->metrictype)
  (metric/undefined UndefinedMetric)
  (metric/absoluteerror AbsoluteErrorMetric)
  (metric/meanabsoluteerror MeanAbsoluteErrorMetric)
  (metric/meanerrorperpixel MeanErrorPerPixelMetric)
  (metric/meansquarederror MeanSquaredErrorMetric)
  (metric/peakabsoluteerror PeakAbsoluteErrorMetric)
  (metric/peaksignaltonoiseratio PeakSignalToNoiseRatioMetric)
  (metric/rootmeansquarederror RootMeanSquaredErrorMetric)
  (metric/normalizedcrosscorrelationerror NormalizedCrossCorrelationErrorMetric)
  (metric/fuzzerror FuzzErrorMetric))

(define-foreign-enum-type (imagelayermethod int)
  (imagelayermethod->int int->imagelayermethod)
  (layer/undefined UndefinedLayer)
  (layer/coalesce CoalesceLayer)
  (layer/compareany CompareAnyLayer)
  (layer/compareclear CompareClearLayer)
  (layer/compareoverlay CompareOverlayLayer)
  (layer/dispose DisposeLayer)
  (layer/optimize OptimizeLayer)
  (layer/optimizeimage OptimizeImageLayer)
  (layer/optimizeplus OptimizePlusLayer)
  (layer/optimizetrans OptimizeTransLayer)
  (layer/removedups RemoveDupsLayer)
  (layer/removezero RemoveZeroLayer)
  (layer/composite CompositeLayer)
  (layer/merge MergeLayer)
  (layer/flatten FlattenLayer)
  (layer/mosaic MosaicLayer)
  (layer/trimbounds TrimBoundsLayer))

(define-foreign-enum-type (compositeoperator int)
  (compositeoperator->int int->compositeoperator)
  (composite/undefined UndefinedCompositeOp)
  (composite/none NoCompositeOp)
  (composite/modulusadd ModulusAddCompositeOp)
  (composite/atop AtopCompositeOp)
  (composite/blend BlendCompositeOp)
  (composite/bumpmap BumpmapCompositeOp)
  (composite/changemask ChangeMaskCompositeOp)
  (composite/clear ClearCompositeOp)
  (composite/colorburn ColorBurnCompositeOp)
  (composite/colordodge ColorDodgeCompositeOp)
  (composite/colorize ColorizeCompositeOp)
  (composite/copyblack CopyBlackCompositeOp)
  (composite/copyblue CopyBlueCompositeOp)
  (composite/copy CopyCompositeOp)
  (composite/copycyan CopyCyanCompositeOp)
  (composite/copygreen CopyGreenCompositeOp)
  (composite/copymagenta CopyMagentaCompositeOp)
  (composite/copyopacity CopyOpacityCompositeOp)
  (composite/copyred CopyRedCompositeOp)
  (composite/copyyellow CopyYellowCompositeOp)
  (composite/darken DarkenCompositeOp)
  (composite/dstatop DstAtopCompositeOp)
  (composite/dst DstCompositeOp)
  (composite/dstin DstInCompositeOp)
  (composite/dstout DstOutCompositeOp)
  (composite/dstover DstOverCompositeOp)
  (composite/difference DifferenceCompositeOp)
  (composite/displace DisplaceCompositeOp)
  (composite/dissolve DissolveCompositeOp)
  (composite/exclusion ExclusionCompositeOp)
  (composite/hardlight HardLightCompositeOp)
  (composite/hue HueCompositeOp)
  (composite/in InCompositeOp)
  (composite/lighten LightenCompositeOp)
  (composite/linearlight LinearLightCompositeOp)
  (composite/luminize LuminizeCompositeOp)
  (composite/minusdst MinusDstCompositeOp)
  (composite/modulate ModulateCompositeOp)
  (composite/multiply MultiplyCompositeOp)
  (composite/out OutCompositeOp)
  (composite/over OverCompositeOp)
  (composite/overlay OverlayCompositeOp)
  (composite/plus PlusCompositeOp)
  (composite/replace ReplaceCompositeOp)
  (composite/saturate SaturateCompositeOp)
  (composite/screen ScreenCompositeOp)
  (composite/softlight SoftLightCompositeOp)
  (composite/srcatop SrcAtopCompositeOp)
  (composite/src SrcCompositeOp)
  (composite/srcin SrcInCompositeOp)
  (composite/srcout SrcOutCompositeOp)
  (composite/srcover SrcOverCompositeOp)
  (composite/modulussubtract ModulusSubtractCompositeOp)
  (composite/threshold ThresholdCompositeOp)
  (composite/xor XorCompositeOp)
  (composite/dividedst DivideDstCompositeOp)
  (composite/distort DistortCompositeOp)
  (composite/blur BlurCompositeOp)
  (composite/pegtoplight PegtopLightCompositeOp)
  (composite/vividlight VividLightCompositeOp)
  (composite/pinlight PinLightCompositeOp)
  (composite/lineardodge LinearDodgeCompositeOp)
  (composite/linearburn LinearBurnCompositeOp)
  (composite/mathematics MathematicsCompositeOp)
  (composite/dividesrc DivideSrcCompositeOp)
  (composite/minussrc MinusSrcCompositeOp)
  (composite/darkenintensity DarkenIntensityCompositeOp)
  (composite/lightenintensity LightenIntensityCompositeOp))

(define-foreign-enum-type (storagetype int)
  (storagetype->int int->storagetype)
  (pixel/undefined UndefinedPixel)
  (pixel/char CharPixel)
  (pixel/double DoublePixel)
  (pixel/float FloatPixel)
  (pixel/integer IntegerPixel)
  (pixel/long LongPixel)
  (pixel/quantum QuantumPixel)
  (pixel/short ShortPixel))

(define-foreign-enum-type (distortimagemethod int)
  (distortimagemethod-> int->distortimagemethod)
  (distortion/undefined UndefinedDistortion)
  (distortion/affine AffineDistortion)
  (distortion/affineprojection AffineProjectionDistortion)
  (distortion/scalerotatetranslate ScaleRotateTranslateDistortion)
  (distortion/perspective PerspectiveDistortion)
  (distortion/perspectiveprojection PerspectiveProjectionDistortion)
  (distortion/bilinearforward BilinearForwardDistortion)
  (distortion/bilinear BilinearDistortion)
  (distortion/bilinearreverse BilinearReverseDistortion)
  (distortion/polynomial PolynomialDistortion)
  (distortion/arc ArcDistortion)
  (distortion/polar PolarDistortion)
  (distortion/depolar DePolarDistortion)
  (distortion/cylinder2plane Cylinder2PlaneDistortion)
  (distortion/plane2cylinder Plane2CylinderDistortion)
  (distortion/barrel BarrelDistortion)
  (distortion/barrelinverse BarrelInverseDistortion)
  (distortion/shepards ShepardsDistortion)
  (distortion/resize ResizeDistortion)
  (distortion/sentinel SentinelDistortion))

(define-foreign-enum-type (magickevaluateoperator int)
  (magickevaluateoperator->int int->magickevaluateoperator)
  (evaluateoperator/undefined UndefinedEvaluateOperator)
  (evaluateoperator/add AddEvaluateOperator)
  (evaluateoperator/and AndEvaluateOperator)
  (evaluateoperator/divide DivideEvaluateOperator)
  (evaluateoperator/leftshift LeftShiftEvaluateOperator)
  (evaluateoperator/max MaxEvaluateOperator)
  (evaluateoperator/min MinEvaluateOperator)
  (evaluateoperator/multiply MultiplyEvaluateOperator)
  (evaluateoperator/or OrEvaluateOperator)
  (evaluateoperator/rightshift RightShiftEvaluateOperator)
  (evaluateoperator/set SetEvaluateOperator)
  (evaluateoperator/subtract SubtractEvaluateOperator)
  (evaluateoperator/xor XorEvaluateOperator)
  (evaluateoperator/pow PowEvaluateOperator)
  (evaluateoperator/log LogEvaluateOperator)
  (evaluateoperator/threshold ThresholdEvaluateOperator)
  (evaluateoperator/thresholdblack ThresholdBlackEvaluateOperator)
  (evaluateoperator/thresholdwhite ThresholdWhiteEvaluateOperator)
  (evaluateoperator/gaussiannoise GaussianNoiseEvaluateOperator)
  (evaluateoperator/impulsenoise ImpulseNoiseEvaluateOperator)
  (evaluateoperator/laplaciannoise LaplacianNoiseEvaluateOperator)
  (evaluateoperator/multiplicativenoise MultiplicativeNoiseEvaluateOperator)
  (evaluateoperator/poissonnoise PoissonNoiseEvaluateOperator)
  (evaluateoperator/uniformnoise UniformNoiseEvaluateOperator)
  (evaluateoperator/cosine CosineEvaluateOperator)
  (evaluateoperator/sine SineEvaluateOperator)
  (evaluateoperator/addmodulus AddModulusEvaluateOperator)
  (evaluateoperator/mean MeanEvaluateOperator)
  (evaluateoperator/abs AbsEvaluateOperator)
  (evaluateoperator/exponential ExponentialEvaluateOperator)
  (evaluateoperator/median MedianEvaluateOperator))

(define-foreign-enum-type (magickfunction int)
  (magickfunction->int int->magickfunction)
  (function/undefined UndefinedFunction)
  (function/polynomial PolynomialFunction)
  (function/sinusoid SinusoidFunction)
  (function/arcsin ArcsinFunction)
  (function/arctan ArctanFunction))

(define-foreign-enum-type (disposetype int)
  (disposetype->int int->disposetype)
  (dispose/unrecognized UnrecognizedDispose)
  (dispose/undefined UndefinedDispose)
  (dispose/none NoneDispose)
  (dispose/background BackgroundDispose)
  (dispose/previous PreviousDispose))

(define-foreign-enum-type (renderingintent int)
  (renderingintent->int int->renderingintent)
  (intent/undefined UndefinedIntent)
  (intent/saturation SaturationIntent)
  (intent/perceptual PerceptualIntent)
  (intent/absolute AbsoluteIntent)
  (intent/relative RelativeIntent))

(define-foreign-enum-type (resolutiontype int)
  (resolutiontype->int int->resolutiontype)
  (resolution/undefined UndefinedResolution)
  (resolution/pixelsperinch PixelsPerInchResolution)
  (resolution/pixelspercentimeter PixelsPerCentimeterResolution))

(define-foreign-enum-type (virtualpixelmethod int)
  (virtualpixelmethod->int int->virtualpixelmethod)
  (virtualpixelmethod/undefined UndefinedVirtualPixelMethod)
  (virtualpixelmethod/background BackgroundVirtualPixelMethod)
  (virtualpixelmethod/constant ConstantVirtualPixelMethod)
  (virtualpixelmethod/dither DitherVirtualPixelMethod)
  (virtualpixelmethod/edge EdgeVirtualPixelMethod)
  (virtualpixelmethod/mirror MirrorVirtualPixelMethod)
  (virtualpixelmethod/random RandomVirtualPixelMethod)
  (virtualpixelmethod/tile TileVirtualPixelMethod)
  (virtualpixelmethod/transparent TransparentVirtualPixelMethod)
  (virtualpixelmethod/mask MaskVirtualPixelMethod)
  (virtualpixelmethod/black BlackVirtualPixelMethod)
  (virtualpixelmethod/gray GrayVirtualPixelMethod)
  (virtualpixelmethod/white WhiteVirtualPixelMethod)
  (virtualpixelmethod/horizontaltile HorizontalTileVirtualPixelMethod)
  (virtualpixelmethod/verticaltile VerticalTileVirtualPixelMethod)
  (virtualpixelmethod/horizontaltileedge HorizontalTileEdgeVirtualPixelMethod)
  (virtualpixelmethod/verticaltileedge VerticalTileEdgeVirtualPixelMethod)
  (virtualpixelmethod/checkertile CheckerTileVirtualPixelMethod))

(define-foreign-enum-type (montagemode int)
  (montagemode->int int->montagemode)
  (mode/undefined UndefinedMode)
  (mode/frame FrameMode)
  (mode/unframe UnframeMode)
  (mode/concatenate ConcatenateMode))

(define-foreign-enum-type (morphologymethod int)
  (morphologymethod->int int->morphologymethod)
  (morphology/undefined UndefinedMorphology)
  (morphology/convolve ConvolveMorphology)
  (morphology/correlate CorrelateMorphology)
  (morphology/erode ErodeMorphology)
  (morphology/dilate DilateMorphology)
  (morphology/erodeintensity ErodeIntensityMorphology)
  (morphology/dilateintensity DilateIntensityMorphology)
  (morphology/distance DistanceMorphology)
  (morphology/open OpenMorphology)
  (morphology/close CloseMorphology)
  (morphology/openintensity OpenIntensityMorphology)
  (morphology/closeintensity CloseIntensityMorphology)
  (morphology/smooth SmoothMorphology)
  (morphology/edgein EdgeInMorphology)
  (morphology/edgeout EdgeOutMorphology)
  (morphology/edge EdgeMorphology)
  (morphology/tophat TopHatMorphology)
  (morphology/bottomhat BottomHatMorphology)
  (morphology/hitandmiss HitAndMissMorphology)
  (morphology/thinning ThinningMorphology)
  (morphology/thicken ThickenMorphology)
  (morphology/voronoi VoronoiMorphology))

(define-foreign-enum-type (previewtype int)
  (previewtype->int int->previewtype)
  (preview/undefined UndefinedPreview)
  (preview/rotate RotatePreview)
  (preview/shear ShearPreview)
  (preview/roll RollPreview)
  (preview/hue HuePreview)
  (preview/saturation SaturationPreview)
  (preview/brightness BrightnessPreview)
  (preview/gamma GammaPreview)
  (preview/spiff SpiffPreview)
  (preview/dull DullPreview)
  (preview/grayscale GrayscalePreview)
  (preview/quantize QuantizePreview)
  (preview/despeckle DespecklePreview)
  (preview/reducenoise ReduceNoisePreview)
  (preview/addnoise AddNoisePreview)
  (preview/sharpen SharpenPreview)
  (preview/blur BlurPreview)
  (preview/threshold ThresholdPreview)
  (preview/edgedetect EdgeDetectPreview)
  (preview/spread SpreadPreview)
  (preview/solarize SolarizePreview)
  (preview/shade ShadePreview)
  (preview/raise RaisePreview)
  (preview/segment SegmentPreview)
  (preview/swirl SwirlPreview)
  (preview/implode ImplodePreview)
  (preview/wave WavePreview)
  (preview/oilpaint OilPaintPreview)
  (preview/charcoaldrawing CharcoalDrawingPreview)
  (preview/jpeg JPEGPreview))

(define-foreign-enum-type (dithermethod int)
  (dithermethod->int int->dithermethod)
  (dithermethod/undefined UndefinedDitherMethod)
  (dithermethod/none NoDitherMethod)
  (dithermethod/riemersma RiemersmaDitherMethod)
  (dithermethod/floydsteinberg FloydSteinbergDitherMethod))

(define-foreign-enum-type (filtertype int)
  (filtertype->int int->filtertype)
  (filter/undefined UndefinedFilter)
  (filter/point PointFilter)
  (filter/box BoxFilter)
  (filter/triangle TriangleFilter)
  (filter/hermite HermiteFilter)
  (filter/hanning HanningFilter)
  (filter/hamming HammingFilter)
  (filter/blackman BlackmanFilter)
  (filter/gaussian GaussianFilter)
  (filter/quadratic QuadraticFilter)
  (filter/cubic CubicFilter)
  (filter/catrom CatromFilter)
  (filter/mitchell MitchellFilter)
  (filter/jinc JincFilter)
  (filter/sinc SincFilter)
  (filter/sincfast SincFastFilter)
  (filter/kaiser KaiserFilter)
  (filter/welsh WelshFilter)
  (filter/parzen ParzenFilter)
  (filter/bohman BohmanFilter)
  (filter/bartlett BartlettFilter)
  (filter/lagrange LagrangeFilter)
  (filter/lanczos LanczosFilter)
  (filter/lanczossharp LanczosSharpFilter)
  (filter/lanczos2 Lanczos2Filter)
  (filter/lanczos2sharp Lanczos2SharpFilter)
  (filter/robidoux RobidouxFilter)
  (filter/sentinel SentinelFilter))

(define-foreign-enum-type (alphachanneltype int)
  (alphachanneltype->int int->alphachanneltype)
  (alphachannel/undefined UndefinedAlphaChannel)
  (alphachannel/activate ActivateAlphaChannel)
  (alphachannel/background BackgroundAlphaChannel)
  (alphachannel/copy CopyAlphaChannel)
  (alphachannel/deactivate DeactivateAlphaChannel)
  (alphachannel/extract ExtractAlphaChannel)
  (alphachannel/opaque OpaqueAlphaChannel)
  (alphachannel/reset ResetAlphaChannel)
  (alphachannel/set SetAlphaChannel)
  (alphachannel/shape ShapeAlphaChannel)
  (alphachannel/transparent TransparentAlphaChannel))

(define-foreign-enum-type (sparsecolormethod int)
  (sparsecolormethod->int int->sparsecolormethod)
  (colorinterpolate/undefined UndefinedColorInterpolate)
  (colorinterpolate/barycentric BarycentricColorInterpolate)
  (colorinterpolate/bilinear BilinearColorInterpolate)
  (colorinterpolate/polynomial PolynomialColorInterpolate)
  (colorinterpolate/shepards ShepardsColorInterpolate)
  (colorinterpolate/voronoi VoronoiColorInterpolate)
  (colorinterpolate/inverse InverseColorInterpolate))

(define-foreign-enum-type (statistictype int)
  (statistictype->int int->statistictype)
  (statistic/undefined UndefinedStatistic)
  (statistic/gradient GradientStatistic)
  (statistic/maximum MaximumStatistic)
  (statistic/mean MeanStatistic)
  (statistic/median MedianStatistic)
  (statistic/minimum MinimumStatistic)
  (statistic/mode ModeStatistic)
  (statistic/nonpeak NonpeakStatistic)
  (statistic/standarddeviation StandardDeviationStatistic))

(define-foreign-enum-type (classtype int)
  (classtype->int int->classtype)
  (class/undefined UndefinedClass)
  (class/direct DirectClass)
  (class/pseudo PseudoClass))

(define-foreign-enum-type (paintmethod int)
  (paintmethod->int int->paintmethod)
  (paintmethod/undefined UndefinedMethod)
  (paintmethod/point PointMethod)
  (paintmethod/replace ReplaceMethod)
  (paintmethod/floodfill FloodfillMethod)
  (paintmethod/filltoborder FillToBorderMethod)
  (paintmethod/reset ResetMethod))

(define-foreign-enum-type (fillrule int)
  (fillrule->int int->fillrule)
  (rule/undefined UndefinedRule)
  (rule/evenodd EvenOddRule)
  (rule/nonzero NonZeroRule))

(define-foreign-enum-type (clippathunits int)
  (clippathunits->int int->clippathunits)
  (clippathunits/undefined UndefinedPathUnits)
  (clippathunits/userspace UserSpace)
  (clippathunits/userspaceonuse UserSpaceOnUse)
  (clippathunits/objectboundingbox ObjectBoundingBox))

(define-foreign-enum-type (stretchtype int)
  (stretchtype->int int->stretchtype)
  (stretch/undefined UndefinedStretch)
  (stretch/normal NormalStretch)
  (stretch/ultracondensed UltraCondensedStretch)
  (stretch/extracondensed ExtraCondensedStretch)
  (stretch/condensed CondensedStretch)
  (stretch/semicondensed SemiCondensedStretch)
  (stretch/semiexpanded SemiExpandedStretch)
  (stretch/expanded ExpandedStretch)
  (stretch/extraexpanded ExtraExpandedStretch)
  (stretch/ultraexpanded UltraExpandedStretch)
  (stretch/any AnyStretch))

(define-foreign-enum-type (styletype int)
  (styletype->int int->styletype)
  (style/undefined UndefinedStyle)
  (style/normal NormalStyle)
  (style/italic ItalicStyle)
  (style/oblique ObliqueStyle)
  (style/any AnyStyle))

(define-foreign-enum-type (linecap int)
  (linecap->int int->linecap)
  (linecap/undefined UndefinedCap)
  (linecap/butt ButtCap)
  (linecap/round RoundCap)
  (linecap/square SquareCap))

(define-foreign-enum-type (linejoin int)
  (linejoin->int int->linejoin)
  (linejoin/undefined UndefinedJoin)
  (linejoin/miter MiterJoin)
  (linejoin/round RoundJoin)
  (linejoin/bevel BevelJoin))

(define-foreign-enum-type (aligntype int)
  (aligntype->int int->aligntype)
  (align/undefined UndefinedAlign)
  (align/left LeftAlign)
  (align/center CenterAlign)
  (align/right RightAlign))

(define-foreign-enum-type (decorationtype int)
  (decorationtype->int int->decorationtype)
  (decoration/undefined UndefinedDecoration)
  (decoration/none NoDecoration)
  (decoration/underline UnderlineDecoration)
  (decoration/overline OverlineDecoration)
  (decoration/linethrough LineThroughDecoration))
